language: java
sudo: false # faster builds
script: cd Java/example-java && mvn install && "mvn cobertura:cobertura"

notifications:
  email: false

jdk:
- oraclejdk8

after_success:
- bash <(curl -s https://codecov.io/bash)
